<a href="https://colab.research.google.com/github/SKnight262/Machine_Learning/blob/main/DataCleanse_01_JUN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, :-1].values
print(x)
y = dataset.iloc[:, -1].values
print(y)
print(type(y))


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:, 1:3] = imputer.fit_transform(x[:, 1:3])
print(x)

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print('x_train:\n', x_train)
print('x_test:\n', x_test)
print('y_train:\n', y_train)
print('y_test:\n', y_test)

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [51]:
print('x_train scaled:\n', x_train)
print('x_test scaled:\n', x_test)

x_train scaled:
 [[ 1.         -0.57735027 -0.57735027 -0.80667524 -0.72132045]
 [ 1.         -0.57735027 -0.57735027  0.61764507  0.58171004]
 [ 1.         -0.57735027 -0.57735027  1.25067632  1.23322529]
 [-1.          1.73205081 -0.57735027 -1.5979643  -1.09361488]
 [-1.         -0.57735027  1.73205081 -0.3319018  -0.44209963]
 [-1.         -0.57735027  1.73205081 -0.20881239 -1.27976209]
 [ 1.         -0.57735027 -0.57735027 -0.49015961  0.11634201]
 [-1.          1.73205081 -0.57735027  1.56719195  1.60551972]]
x_test scaled:
 [[-1.          1.73205081 -0.57735027 -0.01538618 -0.18356184]
 [-1.         -0.57735027  1.73205081 -2.07273774 -1.65205652]]
